package site

import "html/template"

var portableTemplate = template.Must(template.New("portable-roadmap").Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cassor roadmap</title><style>
:root{--bg:#07111f;--panel:#0b1a2b;--card:#101f35;--ink:#f8fafc;--muted:#94a3b8;--line:#1e293b;--accent:#22d3ee;--success:#34d399;--focus:#67e8f9}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top right,#12365b,var(--bg) 48%);color:var(--ink);font:15px ui-sans-serif,system-ui,sans-serif}main{max-width:1240px;margin:auto;padding:32px 20px}.eyebrow{color:var(--accent);font-size:.75rem;font-weight:800;letter-spacing:.18em}h1{font-size:clamp(2rem,5vw,3.5rem);letter-spacing:-.03em;margin:.5rem 0}h2{margin:0;font-size:1.15rem;letter-spacing:-.01em}p{color:var(--muted);line-height:1.6}.stats,.grid{display:grid;gap:14px}.stats{grid-template-columns:repeat(auto-fit,minmax(145px,1fr));margin:28px 0}.grid{grid-template-columns:repeat(auto-fit,minmax(280px,1fr))}.stat,.card{background:linear-gradient(145deg,rgba(16,31,53,.96),rgba(11,26,43,.96));border:1px solid var(--line);border-radius:14px;padding:17px}.stat b{display:block;color:var(--accent);font-size:1.8rem;font-variant-numeric:tabular-nums}.controls{display:flex;flex-wrap:wrap;gap:10px;margin:26px 0}input,select{background:var(--panel);border:1px solid #334155;border-radius:9px;color:var(--ink);font:inherit;padding:10px 12px}input{flex:1 1 260px}select{flex:1 1 150px}input:focus,select:focus,summary:focus{outline:3px solid var(--focus);outline-offset:2px}.card{display:flex;flex-direction:column;min-width:0}.card-title{display:block;color:var(--ink);font-size:1rem;line-height:1.35;overflow-wrap:anywhere}.card-summary{margin:10px 0 0;overflow-wrap:anywhere}.card-footer{margin-top:auto;padding-top:16px}.progress{background:#020617;border-radius:999px;height:7px;margin:0 0 8px;overflow:hidden}.progress span{background:var(--accent);border-radius:inherit;display:block;height:100%}.progress-meta{align-items:center;display:flex;justify-content:space-between}.percentage{color:var(--success);font-variant-numeric:tabular-nums;font-weight:700;min-width:3.4rem;text-align:right}.meta{color:var(--muted);font-size:.85rem}.tag{background:#172f4d;border:1px solid #294766;border-radius:999px;color:#bae6fd;display:inline-block;font-size:.75rem;line-height:1.2;margin:0 5px 0 0;padding:4px 8px}.tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.details{border-top:1px solid var(--line);margin-top:14px;padding-top:12px}details summary{cursor:pointer;color:var(--focus);font-weight:700}.section{margin-top:34px}.section>h2+.grid{margin-top:1rem}.empty{color:var(--muted);font-style:italic}.list{margin:10px 0 0;padding-left:18px}.list li{margin:7px 0}@media(max-width:640px){main{padding:24px 14px}.controls>*{width:100%}.grid{grid-template-columns:1fr}.stat,.card{padding:15px}}
</style></head><body><main><header><div class="eyebrow">CASSOR · PORTABLE ROADMAP</div><h1 id="project"></h1><p>Approved work, delivery progress, and verification evidence. Generated without project documentation or frontend dependencies.</p></header><section class="stats" id="stats"></section><section class="controls" aria-label="Roadmap filters"><input id="search" type="search" placeholder="Search roadmap" aria-label="Search roadmap"><select id="status" aria-label="Filter by status"><option value="">All statuses</option></select><select id="horizon" aria-label="Filter by horizon"><option value="">All horizons</option></select></section><section class="section"><h2>Roadmap</h2><div class="grid" id="items"></div></section><section class="section"><h2>Approved plans and tasks</h2><div class="grid" id="plans"></div></section><section class="section"><h2>Acceptance criteria</h2><div class="grid" id="criteria"></div></section></main><script>
const data={{.Data}},$=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const planItem=new Map(data.plans.map(plan=>[plan.id,plan.item_id])),epicByID=new Map((data.epics||[]).map(epic=>[epic.id,epic]));$('project').textContent=data.project_name;
for(const [id,key] of [['status','status'],['horizon','horizon']]) [...new Set(data.items.map(item=>item[key]).filter(Boolean))].sort().forEach(value=>$(id).insertAdjacentHTML('beforeend','<option>'+esc(value)+'</option>'));
function itemCard(item){const specs=(()=>{try{return JSON.parse(item.specifications||'[]')}catch{return[]}})(),progress=item.status==='Done'?100:Math.max(0,Math.min(100,Number(item.progress)||0)),epic=epicByID.get(item.epic_id),epicTag=epic?'<span class="tag">Epic: '+esc(epic.title)+'</span>':'';const specsHtml=specs.length?'<ul class="list">'+specs.map(spec=>'<li>'+(spec.done?'✓ ':'○ ')+esc(spec.title)+'</li>').join('')+'</ul>':'';return '<article class="card"><strong class="card-title">'+esc(item.title)+'</strong><p class="card-summary">'+esc(item.current_state||item.description||item.rationale||'No description recorded.')+'</p><div class="tags"><span class="tag">'+esc(item.feature_type)+'</span>'+epicTag+'<span class="tag">'+esc(item.status)+'</span><span class="tag">'+esc(item.horizon)+'</span></div><details class="details"><summary>Details</summary><p class="meta">Category: '+esc(item.category)+' · Priority: '+esc(item.priority||'Unassigned')+'</p>'+specsHtml+'</details><div class="card-footer"><div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+esc(progress)+'" aria-label="'+esc(progress)+' percent complete"><span style="width:'+progress+'%"></span></div><div class="progress-meta"><span class="meta">Progress</span><span class="percentage">'+esc(progress)+'%</span></div></div></article>'}
function render(){const query=$('search').value.trim().toLowerCase(),status=$('status').value,horizon=$('horizon').value;const visible=data.items.filter(item=>(!query||[item.title,item.description,item.rationale,item.current_state].join(' ').toLowerCase().includes(query))&&(!status||item.status===status)&&(!horizon||item.horizon===horizon));const statuses=['Planned','Ready','In Progress','Blocked','Done'];$('stats').innerHTML=statuses.map(name=>'<article class="stat"><b>'+visible.filter(item=>item.status===name).length+'</b>'+name+'</article>').join('');$('items').innerHTML=visible.length?visible.map(itemCard).join(''):'<p class="empty">No roadmap items match these filters.</p>';const tasksByPlan=new Map;for(const task of data.tasks){const tasks=tasksByPlan.get(task.plan_id)||[];tasks.push(task);tasksByPlan.set(task.plan_id,tasks)}$('plans').innerHTML=data.plans.length?data.plans.map(plan=>{const tasks=tasksByPlan.get(plan.id)||[];return '<article class="card"><strong>'+esc(plan.item_title)+'</strong><p class="meta">Revision '+esc(plan.revision)+' · '+esc(plan.status)+'</p><ul class="list">'+(tasks.length?tasks.map(task=>'<li><strong>'+esc(task.title)+'</strong> · '+esc(task.status)+(task.outcome?' — '+esc(task.outcome):'')+'</li>').join(''):'<li>No tasks recorded.</li>')+'</ul></article>'}).join(''):'<p class="empty">No approved plans yet.</p>';const itemTitles=new Map(data.items.map(item=>[item.id,item.title]));$('criteria').innerHTML=data.criteria.length?data.criteria.map(criterion=>'<article class="card"><strong>'+esc(itemTitles.get(criterion.ItemID)||'Roadmap item')+'</strong><p>'+esc(criterion.Title)+'</p><span class="tag">'+esc(criterion.Status)+'</span>'+(criterion.Evidence?'<p class="meta">'+esc(criterion.Evidence)+'</p>':'')+'</article>').join(''):'<p class="empty">No acceptance criteria recorded yet.</p>'}
for(const id of ['search','status','horizon']) $(id).addEventListener(id==='search'?'input':'change',render);render();
</script></body></html>`))
